"""Module contains common string."""
INQUIRERPY_KEYBOARD_INTERRUPT: str = "INQUIRERPY_KEYBOARD_INTERRUPT"

INQUIRERPY_POINTER_SEQUENCE: str = "\u276f"
INQUIRERPY_FILL_HEX_SEQUENCE: str = "\u2b22"
INQUIRERPY_EMPTY_HEX_SEQUENCE: str = "\u2b21"
